version: '3.8'

services:
  site-2cybersec:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: site-2cybersec
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site-2cybersec.rule=Host(`2cybersec.com.br`) || Host(`www.2cybersec.com.br`)"
      - "traefik.http.routers.site-2cybersec.entrypoints=web,websecure"
      - "traefik.http.routers.site-2cybersec.tls.certresolver=myresolver"
      - "traefik.http.services.site-2cybersec.loadbalancer.server.port=80"
    networks:
      - web
      - dokploy-network

networks:
  web:
    driver: bridge
  dokploy-network:
    external: true
